name: Animusic
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - libffi=3.4.4
  - openssl=3.0.16
  - pip=25.1
  - python=3.12.9
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025b
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - altgraph==0.17.4
      - networkx==3.4.2
      - numpy==2.2.5
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - packaging==25.0
      - pefile==2023.2.7
      - pyinstaller==6.13.0
      - pyinstaller-hooks-contrib==2025.4
      - pyside6==6.9.0
      - pyside6-addons==6.9.0
      - pyside6-essentials==6.9.0
      - pywin32-ctypes==0.2.3
      - shiboken6==6.9.0
